* bricewge/weechat
Docker image using phusion/baseimage, for runing a WeeChat relay.

* Build
Builded: =docker build -t bricewge/weechat ./x86_64/weechat=

* Using
For example it can be run like this:
#+BEGIN_SRC sh
docker run -t -d -p 22004:22 -p 8004:8004 \
   -h weechat \
   --name weechat \
   -e relaypasswd=password \
   bricewge/weechat
#+END_SRC

** WeeChat variables
The default password to the relay is =password=, this is insecure, set an other one via the relaypasswd environement variable.

** SSH
To connect to the container with SSH you'll need to check out the
[[https://github.com/phusion/baseimage-docker/raw/master/image/insecure_key][phusion/baseimage documentation]].

If have the right key already setup you can do it like as follow.
Find out the ID of the container that you just ran:
=docker ps=
Once you have the ID, look for its IP address with:
=docker inspect -f "{{ .NetworkSettings.IPAddress }}" <ID>=
Now SSH into the container as follows:
=ssh -i /path-to/your_key root@<IP address>=

* TODO
** Choose the name of the user
Don't hardcode bricewge, do the same as the password of the relay.

* Ressources
Example: https://github.com/creack/weechat-docker
