# rpi-gitannex
#
# Version 0.1

FROM bricewge/rpi-raspbian

# Install git-annex
RUN apt-get -y install wget
RUN wget http://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-armel.tar.gz
RUN tar -zxf git-annex-standalone-armel.tar.gz
