* bricewge/transmission
Docker image using phusion/baseimage, for runing transmission web
interface (BitTorrent client).

* Build
Builded: =docker build -t bricewge/transmission ./x86_64/transmission=

* Using
For example it can be run like this:
#+BEGIN_SRC sh
docker run -d -p 22001:22 -p 9091:9091 \
   -h transmission \
   --name transmission \
   -v /mnt/hddold/Torrents:/mnt/Torrents/:rw \
   -v /mnt/hddold/Films:/mnt/Films/:rw \
   -e USER_T=transmission \
   -e PASSWD_T=transmission \
   -e WHITELIST_T=127.0.0.1,192.168.1.* \
   bricewge/transmission
#+END_SRC

** Transmission variables


By default transmission (daemon and web interface) are available
from every hosts, the username is =username=, the password is =password=.
Which is unsafe think to restrict all of this.

** SSH
To connect to the container with SSH you'll need to check out the
[[https://github.com/phusion/baseimage-docker/raw/master/image/insecure_key][phusion/baseimage documentation]].

If have the right key already setup you can do it like as follow.
Find out the ID of the container that you just ran:
=docker ps=
Once you have the ID, look for its IP address with:
=docker inspect -f "{{ .NetworkSettings.IPAddress }}" <ID>=
Now SSH into the container as follows:
=ssh -i /path-to/your_key root@<IP address>=

* Todo
** use dotfiles
** update blocklist
** ¿generate hash of the password instead of a clear one?
** ¿set a default username and password?
